- networkx==3.3
- python==3.12.3
- pytorch==2.2.2
- copent==0.5.5
- sentence-transformers==3.0.1
- torch-cluster==1.6.3
- torch-geometric==2.5.3
- torch-scatter==2.1.2
- torch-sparse==0.6.18
- torch-spline-conv==1.2.2

